# Generated by Django 5.1.1 on 2024-11-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_comm_comment_liked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
